recipebook/recepies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('category/<str:category>/',views.recipes_by_category, name='recipes_by_category'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("my_recipes", views.my_recipes, name="my_recipes"),
    path("register", views.register, name="register"),
    path('recipe/add/', views.recipe_add, name='recipe_add'),
    path('recipes/edit/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('recipe/<int:recipe_id>', views.recipe_details, name='recipe_details'),
    path('search/',views.search, name='search'),
    path('shopping-list/', views.view_shopping_list, name='view_shopping_list'),
    path('add-to-shopping-list/<int:recipe_id>/<path:ingredient_name>/', views.add_to_shopping_list, name='add_to_shopping_list'),
    path('remove-from-shopping-list/<int:recipe_id>/<path:ingredient_name>/', views.remove_from_shopping_list, name='remove_from_shopping_list'),
    path('delete-list-item/<int:item_id>/', views.delete_list_item, name='delete_list_item'),
    path('add-to-favorites/<int:recipe_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('favorites/', views.list_favorites, name='favorites'),
    path('your_fridge/', views.your_fridge, name='your_fridge'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("recepies.urls"))
]

recipebook/recepies/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator



# Create your models here.

class Category(models.Model):
  title = models.CharField(max_length=100)

  def __str__(self):
    return self.title
  
class Ingredient(models.Model):
  name = models.CharField(max_length=255, unique=True)
  quantity = models.CharField(max_length=100)
  unit = models.CharField(max_length=50)

  def __str__(self):
    return f"{self.quantity} {self.unit} {self.name}"


# Difficulty levels for the dropdown menu
class DifficultyLevel(models.TextChoices):
  EASY= 'Easy'
  MEDIUM = 'Medium'
  HARD = 'Hard'

class Recipe(models.Model):
  title = models.CharField(max_length=128)
  serving = models.PositiveIntegerField()
  preparation_time = models.PositiveIntegerField()
  difficulty = models.CharField(
    max_length=6,
    choices=DifficultyLevel.choices,
    default=DifficultyLevel.EASY
  )
  raw_ingredients = models.TextField()
  ingredients = models.ManyToManyField(Ingredient, related_name='recipes')
  preparation = models.TextField()
  image = models.ImageField(upload_to='recepies/', null=True, blank=True) 
  categories = models.ManyToManyField(Category, related_name='recipes')
  ratings = models.JSONField(default=dict)
  average_rating = models.FloatField(default=0.0)
  created_at = models.DateTimeField(auto_now_add=True)
  creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="creator_recipe")
  comments = models.ManyToManyField('Comment', related_name="comments_on_recipe", blank=True)


  def update_rating(self, user, new_rating):
    rating_obj, created = Rating.objects.get_or_create(user=user, recipe=self, defaults={'score': new_rating})
    if not created:
        rating_obj.score = new_rating
        rating_obj.save()
    self._update_average_rating()

  def _update_average_rating(self):
      all_ratings = self.recipe_ratings.all()
      total_rating = sum(rating.score for rating in all_ratings)
      total_votes = all_ratings.count()
      self.average_rating = total_rating / total_votes if total_votes else 0
      self.save()

  def __str__(self):
    return self.title

  
  def get_preparation_section(self):
        return self.preparation.split('\n') 
  
  def get_absolute_url(self):
        return reverse('recipe_detail', kwargs={'pk': self.pk})
  
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_ratings")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="recipe_ratings")
    score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

    class Meta:
        unique_together = ('user', 'recipe')  # Biztosítja, hogy minden felhasználó csak egyszer értékeljen egy receptet

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'recipe')

    def __str__(self):
        return f'{self.user.username} - {self.recipe.title}'

class ShoppingList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='shopping_list')
    ingredients = models.ManyToManyField(Ingredient, through='ShoppingListItem')

class ShoppingListItem(models.Model):
    shopping_list = models.ForeignKey(ShoppingList, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    purchased = models.BooleanField(default=False)

class Comment(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="user")
  recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="comment")
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)

recipebook/recepies/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import RatingForm, CommentForm, FridgeForm, RecipeForm
from .models import Recipe, ShoppingList, ShoppingListItem, Category, Ingredient, Rating, Favorite, Comment
from .utils import paginate_with_page_range, get_categories_and_shopping_list_count, handle_ingredient_operation, get_ratings_info, parse_ingredients
from django.db.models import Q




def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "recepies/register.html", {"message": "Passwords must match."})

        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "recepies/register.html", {"message": "Username already taken."})
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "recepies/register.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "recepies/login.html", {"message": "Invalid username and/or password."})
    else:
        return render(request, "recepies/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def index(request):
    categories, shopping_list_items_count = get_categories_and_shopping_list_count(request.user)
    recipes = Recipe.objects.all().order_by('-created_at')
    paginated_recipes, page_range, last_two_pages = paginate_with_page_range(request, recipes, per_page=12)

    return render(request, 'recepies/index.html', {
        'categories': categories,
        'recipes': paginated_recipes,
        'page_range': page_range,
        'last_two_pages': last_two_pages,
        'shopping_list_items_count': shopping_list_items_count,
    })

def recipe_add(request):
    categories, shopping_list_items_count = get_categories_and_shopping_list_count(request.user)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            new_recipe = form.save(commit=False)
            new_recipe.creator = request.user
            new_recipe.save()
            raw_ingredients = form.cleaned_data['raw_ingredients']
            ingredients_data = parse_ingredients(raw_ingredients)
            for quantity, unit, name in ingredients_data:
                ingredient, created = Ingredient.objects.get_or_create(name=name.strip(), defaults={'quantity': quantity, 'unit': unit})
                new_recipe.ingredients.add(ingredient)
            new_recipe.save()
            form.save_m2m()
            return redirect('index')
    else:
        form = RecipeForm()
    return render(request, 'recepies/recipe_form.html', {
        'form': form, 'categories': categories, 'shopping_list_items_count': shopping_list_items_count,
    })



def edit_recipe(request, recipe_id):
    categories, shopping_list_items_count = get_categories_and_shopping_list_count(request.user)
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            updated_recipe = form.save(commit=False)
            updated_recipe.save()
            updated_recipe.ingredients.clear()
            raw_ingredients = form.cleaned_data['raw_ingredients']
            ingredients_data = parse_ingredients(raw_ingredients)
            for quantity, unit, name in ingredients_data:
                ingredient, created = Ingredient.objects.get_or_create(name=name.strip(), defaults={'quantity': quantity, 'unit': unit})
                if not created:
                    ingredient.quantity = quantity
                    ingredient.unit = unit
                    ingredient.save()
                updated_recipe.ingredients.add(ingredient)
            updated_recipe.save()
            form.save_m2m()
            return redirect('recipe_details', recipe_id=recipe_id)
    else:
        form = RecipeForm(instance=recipe)
    return render(request, 'recepies/edit_recipe.html', {
        'form': form, 'recipe': recipe, 'categories': categories, 'shopping_list_items_count': shopping_list_items_count,
    })

def my_recipes(request):
    categories, shopping_list_items_count = get_categories_and_shopping_list_count(request.user)
    recipes = Recipe.objects.filter(creator=request.user)
    paginated_recipes, page_range, last_two_pages = paginate_with_page_range(request, recipes, per_page=12)

    return render(request, 'recepies/my_recipes.html', {
        'categories': categories, 'recipes': paginated_recipes, 'page_range': page_range, 'last_two_pages': last_two_pages, 'shopping_list_items_count': shopping_list_items_count,
    })

def recipe_details(request, recipe_id):
    categories, shopping_list_items_count = get_categories_and_shopping_list_count(request.user)
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    already_rated = False
    user_favorite_recipes = []

    if request.user.is_authenticated:
        user_favorite_recipes = [fav.recipe for fav in Favorite.objects.filter(user=request.user)]
        already_rated = Rating.objects.filter(user=request.user, recipe=recipe).exists()

    ratings, total_ratings = get_ratings_info(recipe)

    comment_form = CommentForm()

    if request.method == 'POST' and request.user.is_authenticated:
        if "comment_form" in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.cleaned_data["content"]
                new_comment = Comment(recipe=recipe, user=request.user, content=comment)
                new_comment.save()
                recipe.comments.add(new_comment)
                recipe.save()
                return HttpResponseRedirect(reverse('recipe_details', args=[recipe_id]) + '?submitted=true')

        elif "ratings" in request.POST:
            form = RatingForm(request.POST)
            if form.is_valid() and not already_rated:
                new_rating = form.cleaned_data['ratings']
                Rating.objects.create(user=request.user, recipe=recipe, score=new_rating)
                recipe.update_rating(request.user, int(new_rating))
                return HttpResponseRedirect(reverse('recipe_details', args=[recipe_id]) + '?submitted=true')

    context = {
        "recipe": recipe,
        "user_favorite_recipes": user_favorite_recipes,
        'ratings': ratings,
        'total_ratings': total_ratings,
        'form': RatingForm(),
        'already_rated': already_rated,
        "commentForm": CommentForm(),
        "comments": recipe.comments.all().order_by('-created_at'),
        'categories': categories,
        'shopping_list_items_count': shopping_list_items_count,
    }

    return render(request, "recepies/recipe_details.html", context)



def recipes_by_category(request, category):
    categories, shopping_list_items_count = get_categories_and_shopping_list_count(request.user)
    category = Category.objects.get(title=category)
    recipes = Recipe.objects.filter(categories=category).order_by('title')
    paginated_recipes, page_range, last_two_pages = paginate_with_page_range(request, recipes, per_page=12)

    return render(request, 'recepies/recipes_by_category.html', {
        'categories': categories, 'category': category, 'recipes': paginated_recipes, 'page_range': page_range, 'last_two_pages': last_two_pages, 'shopping_list_items_count': shopping_list_items_count,
    })

def search(request):
    categories, shopping_list_items_count = get_categories_and_shopping_list_count(request.user)
    query = request.GET.get('query', '')
    if query:
        recipes = Recipe.objects.filter(title__icontains=query)
    else:
        recipes = Recipe.objects.none()

    paginated_recipes, page_range, last_two_pages = paginate_with_page_range(request, recipes, per_page=12)

    return render(request, 'recepies/search.html', {
        'categories': categories, 'query': query, 'recipes': paginated_recipes, 'page_range': page_range, 'last_two_pages': last_two_pages, 'shopping_list_items_count': shopping_list_items_count,
    })

def add_to_shopping_list(request, recipe_id, ingredient_name):
    return handle_ingredient_operation(request, recipe_id, ingredient_name, 'add')

def remove_from_shopping_list(request, recipe_id, ingredient_name):
    return handle_ingredient_operation(request, recipe_id, ingredient_name, 'remove')

def view_shopping_list(request):
    categories, shopping_list_items_count = get_categories_and_shopping_list_count(request.user)
    shopping_list, created = ShoppingList.objects.get_or_create(user=request.user)
    return render(request, 'recepies/shopping_list.html', {
        'shopping_list': shopping_list, 'categories': categories, 'shopping_list_items_count': shopping_list_items_count,
    })

def delete_list_item(request, item_id):
    if request.method == 'POST':
        list_item = ShoppingListItem.objects.get(id=item_id)
        shopping_list = list_item.shopping_list
        list_item.delete()

recipebook/recepies/templates/recepies/edit_recipe.html
{% extends "recepies/layout.html" %}
{% block body_class %}add-recipe-background{% endblock %}
{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
      <div class="col-lg-8 col-md-8">
          <div class="card new_recipe_card shadow-sm mb-5">
              <div class="card-body">
                <h5 class="card-title text-center mb-4">Edit Recipe</h5>
                <div class="form-wrapper">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.title.label_tag }}
                            {{ form.title }}
                        </div>
                        
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                {{ form.serving.label_tag }}
                                {{ form.serving }}
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.preparation_time.label_tag }}
                                {{ form.preparation_time }}
                            </div>
                            <div class="form-group col-md-4">
                                <div class="d-flex flex-column">
                                    {{ form.difficulty.label_tag }}
                                    {{ form.difficulty }}
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {{ form.raw_ingredients.label_tag }}
                            {{ form.raw_ingredients }}
                        </div>
                        
                        <div class="form-group">
                            {{ form.preparation.label_tag }}
                            {{ form.preparation }}
                        </div>
                        
                    <div class="form-group mb-4">
                            {{ form.image.label_tag }}
                            <div>
                                {% if form.image.value %}
                                    <img src="{{ form.image.value.url }}" alt="Current Image" class="img-fluid mb-2" style="max-height: 200px;">
                                {% endif %}
                                {{ form.image }}
                            </div>
                        </div>
                
                        <div class="form-group mb-4">
                            {{ form.categories.label_tag }}
                            <div class="form-inline">
                                {% for checkbox in form.categories %}
                                    <div class="form-check form-check-inline">
                                        {{ checkbox }}
                                        {{ checkbox.label_tag }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                                
                        <button type="submit" class="btn btn-primary submit-btn mt-3">Update Recipe</button>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>


{% endblock %}

recipebook/recepies/templates/recepies/favorites.html
{% extends "recepies/layout.html" %} 
{% block body_class %}recipes-background{% endblock %}
{% block content %}

<h2 class="category-title  mt-4 ml-auto mr-auto  mb-4 p-2 text-center text-light bg-dark">Favorites</h2>

{% include "recepies/recipe_cards.html" with object_list=recipes %}
{% include "recepies/pagination.html" with object_list=recipes %}

{% endblock %}

recipebook/recepies/templates/recepies/index.html
{% extends "recepies/layout.html" %} 
{% block body_class %}recipes-background{% endblock %}
{% block content %}

{% include "recepies/recipe_cards.html" with object_list=recipes %}
{% include "recepies/pagination.html" with object_list=recipes %}

{% endblock %}

recipebook/recepies/templates/recepies/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
  <head>
    <title>{% block title %}CS50 Recipe Book{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="{% static 'recepies/style.css' %}" rel="stylesheet" />

    <style>
    
    .main-content {
        
        padding: 1rem;
        opacity: 0.99;
    }

    </style>
  </head>
  <body class="{% block body_class %}{% endblock %}">
 
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'recepies/images/Colorful_book.webp' %}" alt="Logo" style="height: 40px;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Recipes</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categories
                        </a>
                        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
                            {% for category in categories %}
                            <a class="dropdown-item nav-link" href="{% url 'recipes_by_category' category.title %}">{{ category.title }}</a>
                            {% endfor %}
                        </div>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'your_fridge' %}">What's in your fridge?</a>
                        </li>

                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'recipe_add' %}">Add Recipe</a>
                            </li>
                        
                        {% endif %}
                        <li class="nav-item">
                            <form action="{% url 'search' %}" method="get" class="d-flex">
                                <input  name="query" class="form-control ml-2 search-input" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success ml-2 my-sm-0" type="submit">Search</button>
                            </form>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto"> 
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu  bg-dark" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item nav-link" href="{% url 'my_recipes' %}">My recipes</a>
                                <a class="dropdown-item nav-link" href="{% url 'favorites' %}">Favorites</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item nav-link" href="{% url 'view_shopping_list' %}"><i class="bi bi-cart4"></i>  <span class="badge badge-light">{{shopping_list_items_count}}</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    
    <div class="container pt-3 {% block container_class %}{% endblock %}">
        {% block content %}
        {% endblock %}
    </div>
    

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

  </body>
</html>

recipebook/recepies/templates/recepies/login.html
{% extends "recepies/layout.html" %}
{% block body_class %}login-body{% endblock %}
{% block container_class %}login-section{% endblock %}
{% block content %}

<div class="login-container">
    <div class="login-image"></div>
    <div class="login-form">
        <div class="card bg-transparent text-light login-card">
            <div class="card-header"><h2>Login</h2></div>
            {% if message %}
                <div class="alert alert-danger" role="alert">
                    <div>{{ message }}</div>
                </div>
            {% endif %}
            <div class="card-body">
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Login">
                </form>
            </div>
            <div class="card-footer">
                Don't have an account? <a href="{% url 'register' %}" class="text-warning">Register here.</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

recipebook/recepies/templates/recepies/my_recipes.html
{% extends "recepies/layout.html" %}
{% block body_class %}recipes-background{% endblock %}
{% block content %}

<h2 class="category-title  mt-4 ml-auto mr-auto  mb-4 p-2 text-center text-light bg-dark">My Recipes</h2>

{% include "recepies/recipe_cards.html" with object_list=recipes %}
{% include "recepies/pagination.html" with object_list=recipes %}

{% endblock %}

recipebook/recepies/templates/recepies/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center ">
    {% if object_list.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1&query={{ query }}" aria-label="First">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% endif %}

    {% if page_range|first > 1 %}
      <li class="page-item"><span class="page-link">...</span></li>
    {% endif %}

    {% for num in page_range %}
      <li class="page-item {% if num == object_list.number %}active{% endif %}">
        <a class="page-link" href="?page={{ num }}&query={{ query }}">{{ num }}</a>
      </li>
    {% endfor %}

    {% if page_range|last < last_two_pages|first %}
      <li class="page-item"><span class="page-link">...</span></li>
    {% endif %}

    {% for num in last_two_pages %}
      {% if num > page_range|last %}
        <li class="page-item {% if num == object_list.number %}active{% endif %}">
          <a class="page-link" href="?page={{ num }}&query={{ query }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if object_list.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ object_list.paginator.num_pages }}&query={{ query }}" aria-label="Last">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>

recipebook/recepies/templates/recepies/recipes_by_category.html
{% extends "recepies/layout.html" %}
{% block body_class %}recipes-background{% endblock %}
{% block content %}

<h2 class="category-title p-2 mb-4 mr-auto ml-auto text-center text-light bg-dark">{{ category }}</h2>

{% include "recepies/recipe_cards.html" with object_list=recipes %}
{% include "recepies/pagination.html" with object_list=recipes %}

{% endblock %}

recipebook/recepies/templates/recepies/search.html
{% extends "recepies/layout.html" %} 
{% block body_class %}recipes-background{% endblock %}
{% block content %}
<h2 class="search-info p-2 mb-4 mr-auto ml-auto text-center text-light bg-dark">Search result(s): "{{ query }}"</h2>


{% include "recepies/recipe_cards.html" with object_list=recipes %}
{% include "recepies/pagination.html" with object_list=recipes %}




{% endblock %}

recipebook/recepies/templates/recepies/shopping_list.html
{% extends "recepies/layout.html" %}
{% load format_quantity %}
{% load static %}
{% block body_class %}shopping-list-background{% endblock %}
{% block content %}

<div class"shopping-container">
  <h2 class="mb-4 text-center">Shopping List</h2>
  
  <section class="exotic-style">
    <ul id="shoppingList" class="mb-4">
        {% for item in shopping_list.shoppinglistitem_set.all %}
        <li id="item-{{ item.id }}">
            <input id="item-{{ item.id }}-0" type="checkbox" onchange="toggleStrikethrough(this);">
            <label for="item-{{ item.id }}-0">
                {{ item.ingredient.quantity|format_quantity }} {{ item.ingredient.unit }} {{ item.ingredient.name }}
            </label>
            <button type="button" class="btn btn-danger" onclick="deleteListItem({{ item.id }})"><i class="bi bi-trash3"></i></button>
        </li>
        {% empty %}
        <li class="justify-content-center"> The list is empty</li>
        {% endfor %}

    </ul>
  </section>
</div>


<script src="{% static 'recepies/js/shopping_list.js' %}"></script>

  {% endblock %}